[project]
name = "monkeyjp-basic-inventory-agent-loop-ai"
version = "0.1.0"
description = "AI inventory agent using FastAPI, Groq and tool calling"
readme = "README.md"
authors = [
    { name = "monkeyjp", email = "43521145+monkeyjp@users.noreply.github.com" }
]
requires-python = ">=3.14"

dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "openai>=3.14.1",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.53.0",
]